# Generated by Django 5.1.1 on 2024-09-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='company ati')),
                ('desc', models.TextField(verbose_name='companiys haqqinda')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo:')),
                ('pub_date', models.DateField(verbose_name='Company ashilgan waqiti:')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='kurs ati')),
                ('desc', models.TextField(verbose_name='kurs haqqinda')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kurs baxasi')),
                ('data', models.DateTimeField(verbose_name='kurs neshe ay dawam etedi')),
                ('count_of_lessons', models.BigIntegerField(verbose_name='sabaxlar sani ')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='mentordin F.I.O ')),
                ('desc', models.TextField(verbose_name='mentor haqqinda')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Komment text:')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Qosilgan waqit')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lear_code.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='courses',
            field=models.ManyToManyField(related_name='companies', to='lear_code.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor', to='lear_code.mentor'),
        ),
        migrations.AddField(
            model_name='company',
            name='mentors',
            field=models.ManyToManyField(related_name='companies', to='lear_code.mentor'),
        ),
    ]
